### ISSUE TITLE
Initialization of g and b is not done properly

### ISSUE THREAD

**Issue by SDNAFIO** [zoli333/Weight-Normalization#1]
Looking at the code for the initialization for the g and b parameter,
it seems like the actual assignment operation is never called.

The assignment operations are created, but never executed:
https://github.com/zoli333/Weight-Normalization/blob/f4939760ebfcc02702159b2cf6424e02336ba1e6/nn.py#L143-L144

(see also: https://stackoverflow.com/a/34220750/9562563 if the behaviour of tf.assign is unclear)

This seems to be the case for both the dense and conv2d layer.

**Comment by zoli333** [comment]
Thank you!
I think it is running correctly, like in the following example:

      import tensorflow as tf
      x = tf.Variable(0)
      x = x.assign(1)
      z = 10 + x
      with tf.Session() as sess:
            sess.run(tf.global_variables_initializer())
            print sess.run(z)

result is 11, which is correct. The initialization part in init_forward step in train.py is called inside of the session, so I think this will also be runned.

      if epoch==0:
            sess.run(init_forward,feed_dict={x_init: trainx_white[:init_batch_size]})

I assume this will be forcing the graph to add the assign nodes, and running them (because I run this operation in the session by calling init_forward template in train.py, see the templates separately for initialization and for training in train.py). 

The tf.assign operation definition I think is not necessary, the same behavior happens when adding tf.control_dependencies() which gives the same result. However it would be much more elegant to define operations for the assigns with tf.assign function, return these opearations also in conv2d and dense layers, and calling them directly in the session.

**Comment by meowcakes** [comment]
In your example z has a dependency on x, so of course the assignment operation will be run. His point is that nothing has a dependency on the assign ops in the initialization code, so of course they will never be executed.

**Comment by zoli333** [comment]
so thats why the tf.assign should be used instead, and use tf.control_dependencies instead?

**Comment by meowcakes** [comment]
You can have a look at the implementation of weight normalization here: https://github.com/CompVis/vunet/blob/master/nn.py#L36

Since x has a dependency on g and b assign ops during initialization, they are forced to be run.

**Comment by zoli333** [comment]
I got it thank you for the explanation, and for the link also. They use tf.assign instead.
Very nice repository. I will correct this...

**Comment by zoli333** [comment]
Another question how can I debug these operations?

**Comment by meowcakes** [comment]
I usually just wrap the op in a `tf.Print`. So you can try:
```
g = tf.assign(...)
g = tf.Print(g, [g], message='test ')
```
If nothing gets printed then your op is not being executed.
